import type { Metadata } from "next";
import "./globals.css";
import ShowNav from "@/components/ShowNav";
import { Providers } from "@/redux/Provider";

export const metadata: Metadata = {
  title: "SAAS Event Platform",
  description: "Generated by Himanshu Chauhan",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {" "}
        <Providers>
        <ShowNav />
        {children}
        </Providers>
      </body>
    </html>
  );
}
